'use client';

import React from 'react';
import { DESIGN } from '@/lib/design';

export function HealthDisclaimer({
  variant = 'full',
}: {
  variant?: 'full' | 'compact' | 'onboarding';
}) {
  const textStyle: React.CSSProperties = {
    fontFamily: DESIGN.typography.sansSerif,
    fontSize: variant === 'compact' ? '11px' : '13px',
    color: variant === 'compact' ? 'rgba(255,255,255,0.45)' : DESIGN.colors.textSecondary,
    lineHeight: 1.5,
    margin: 0,
  };

  const linkStyle: React.CSSProperties = {
    color: DESIGN.colors.gold,
    textDecoration: 'underline',
  };

  if (variant === 'compact') {
    return (
      <p style={textStyle}>
        ALCHM is not therapy. Khepera is AI, not a medical professional. In crisis, call{' '}
        <a href="tel:988" style={linkStyle} aria-label="Call 988 Suicide and Crisis Lifeline">
          988
        </a>
        .
      </p>
    );
  }

  return (
    <div
      style={{
        backgroundColor: DESIGN.colors.bgElevated,
        border: `1px solid ${DESIGN.colors.borderLight}`,
        borderRadius: DESIGN.radius.lg,
        padding: '16px',
      }}
    >
      <p style={textStyle}>
        ALCHM is a self-reflection and journaling tool. Khepera is an AI companion powered by artificial intelligence,
        not a therapist, counselor, or medical professional. ALCHM does not diagnose, treat, cure, or prevent any
        medical or mental health condition.
      </p>
      <p style={{ ...textStyle, marginTop: '10px' }}>
        If you are in crisis, call or text{' '}
        <a href="tel:988" style={linkStyle} aria-label="Call 988 Suicide and Crisis Lifeline">
          988
        </a>{' '}
        (Suicide &amp; Crisis Lifeline) or text HOME to{' '}
        <a href="sms:741741&body=HOME" style={linkStyle} aria-label="Text Crisis Text Line">
          741741
        </a>
        .
      </p>
      {variant === 'onboarding' ? (
        <p style={{ ...textStyle, marginTop: '12px', fontStyle: 'italic' }}>
          Khepera&apos;s reflections are generated by artificial intelligence. They are not professional advice.
        </p>
      ) : null}
    </div>
  );
}
