import type React from 'react';

export const DESIGN = {
  colors: {
    bgDeep: 'var(--color-moss-900)',
    bgSurface: 'var(--surface-base)',
    bgElevated: 'var(--surface-elevated)',
    bgWarm: 'var(--surface-focus)',
    bgQuiet: 'var(--surface-quiet)',
    bgHeld: 'var(--surface-held)',
    bgReflective: 'var(--surface-reflective)',
    sageMuted: 'var(--color-sage-500)',
    sage: 'var(--color-sage-600)',
    sageLight: 'var(--color-sage-400)',
    sageBright: 'var(--color-sage-300)',
    goldDim: 'var(--color-gold-400)',
    gold: 'var(--color-gold-500)',
    goldBright: 'var(--color-gold-600)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    emotionCalm: 'var(--color-emotion-calm)',
    emotionHeavy: 'var(--color-emotion-heavy)',
    emotionHope: 'var(--color-emotion-hope)',
    emotionCool: 'var(--color-emotion-cool)',
    textKhepera: 'var(--khepera-text)',
    onDark: 'var(--color-text-primary)',
    onDarkMuted: 'var(--color-text-secondary)',
    onDarkSubtle: 'var(--color-text-muted)',
    kheperaMuted: 'var(--color-text-secondary)',
    onLight: 'var(--color-moss-900)',
    error: 'var(--color-bark-400)',
    success: 'var(--color-sage-500)',
    border: 'var(--border-muted)',
    borderLight: 'var(--border-subtle)',
    cardBg: 'var(--surface-base)',
    cardBgHover: 'var(--surface-elevated)',
  },
  typography: {
    sansSerif: 'var(--font-family-body)',
    serif: 'var(--font-family-heading)',
    ui: 'var(--font-family-body)',
    sizes: {
      xs: '12px',
      sm: '13px',
      base: '16px',
      lg: '18px',
      xl: '24px',
      xxl: '30px',
      display: '42px',
    },
    weights: {
      light: 300,
      regular: 400,
      medium: 500,
      semibold: 500,
    },
    lineHeights: {
      tight: 1.14,
      normal: 1.45,
      relaxed: 1.55,
    },
  },
  spacing: {
    xs: 'var(--space-1)',
    sm: 'var(--space-2)',
    md: 'var(--space-4)',
    lg: 'var(--space-6)',
    xl: 'var(--space-8)',
    xxl: 'var(--space-12)',
    pagePadding: 'var(--page-padding-x)',
    safeBottom: 'calc(72px + env(safe-area-inset-bottom, 0px))',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    full: 'var(--radius-pill)',
  },
  shadows: {
    card: 'var(--shadow-card)',
    elevated: 'var(--shadow-surface)',
    glow: 'var(--shadow-focus)',
    quiet: 'var(--shadow-soft)',
    held: 'var(--shadow-held)',
    reflective: 'var(--shadow-reflective)',
  },
  transitions: {
    fast: '150ms ease',
    normal: '220ms cubic-bezier(0.22, 1, 0.36, 1)',
    slow: '360ms cubic-bezier(0.22, 1, 0.36, 1)',
  },
} as const;

export const cardStyle = (elevated = false): React.CSSProperties => ({
  background: elevated ? DESIGN.colors.bgElevated : DESIGN.colors.bgSurface,
  borderRadius: DESIGN.radius.lg,
  border: elevated ? 'var(--border-visible)' : DESIGN.colors.border,
  padding: elevated ? DESIGN.spacing.lg : DESIGN.spacing.md,
  boxShadow: elevated ? DESIGN.shadows.elevated : DESIGN.shadows.card,
  backdropFilter: 'blur(14px)',
  WebkitBackdropFilter: 'blur(14px)',
  transition:
    'transform 220ms cubic-bezier(0.22, 1, 0.36, 1), box-shadow 220ms ease, border-color 220ms ease, background 220ms ease',
});

export const pageContainerStyle: React.CSSProperties = {
  minHeight: '100dvh',
  background: DESIGN.colors.bgSurface,
  color: DESIGN.colors.textPrimary,
  fontFamily: DESIGN.typography.ui,
  paddingLeft: DESIGN.spacing.pagePadding,
  paddingRight: DESIGN.spacing.pagePadding,
  paddingBottom: DESIGN.spacing.safeBottom,
};
