'use client';

import { getEntries } from '@/lib/journal';
import { generateInsightReport } from '@/lib/insights';

export interface TherapySummary {
  generatedAt: string; // ISO
  periodCovered: string;
  entryCount: number;
  moodSummary: string;
  topThemes: string[];
  temporalNotes: string[];
  userSelectedQuotes: string[];
  disclaimer: string;
}

function fmt(d: Date): string {
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function generateTherapySummary(selectedEntryIds: string[]): TherapySummary {
  const entries = getEntries();
  const report = generateInsightReport();

  const times = entries
    .map((e) => new Date(e.createdAt || e.updatedAt).getTime())
    .filter((t) => Number.isFinite(t));
  const earliest = times.length ? new Date(Math.min(...times)) : new Date();
  const latest = times.length ? new Date(Math.max(...times)) : new Date();

  const moodSummary =
    report.moodPatterns.length > 0
      ? `Most frequent moods: ${report.moodPatterns
          .slice(0, 3)
          .map((m) => `${m.mood} (${m.percentage}%, ${m.trend})`)
          .join(', ')}`
      : 'Not enough mood data yet.';

  const topThemes = report.themePatterns.slice(0, 5).map((t) => t.theme);
  const temporalNotes = report.temporalInsights.map((i) => i.description);

  const selected = entries.filter((e) => selectedEntryIds.includes(e.id));
  const userSelectedQuotes = selected.map((e) => {
    const date = new Date(e.createdAt || e.updatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    const mood = typeof e.mood === 'number' ? ` [${e.mood}]` : '';
    const text = (e.content || '').replace(/\s+/g, ' ').trim().slice(0, 300);
    return `${date}${mood}: "${text}${text.length >= 300 ? '…' : ''}"`;
  });

  return {
    generatedAt: new Date().toISOString(),
    periodCovered: `${fmt(earliest)} – ${fmt(latest)}`,
    entryCount: entries.length,
    moodSummary,
    topThemes,
    temporalNotes,
    userSelectedQuotes,
    disclaimer:
      'Generated by ALCHM. This is a self-reported summary from a journaling app, not a clinical assessment. ALCHM is not a medical device. Khepera (the AI companion) is not a therapist.',
  };
}

export function formatSummaryAsText(summary: TherapySummary): string {
  const lines: string[] = [];
  lines.push('═══ ALCHM Journal Summary ═══');
  lines.push('');
  lines.push(`Generated: ${new Date(summary.generatedAt).toLocaleString('en-US')}`);
  lines.push(`Period: ${summary.periodCovered}`);
  lines.push(`Entries: ${summary.entryCount}`);
  lines.push('');
  lines.push('── Mood Overview ──');
  lines.push(summary.moodSummary);
  lines.push('');

  if (summary.topThemes.length) {
    lines.push('── Recurring Themes ──');
    for (const t of summary.topThemes) lines.push(`  • ${t}`);
    lines.push('');
  }

  if (summary.temporalNotes.length) {
    lines.push('── Patterns ──');
    for (const n of summary.temporalNotes) lines.push(`  ${n}`);
    lines.push('');
  }

  if (summary.userSelectedQuotes.length) {
    lines.push('── Selected Excerpts ──');
    for (const q of summary.userSelectedQuotes) lines.push(`  ${q}`);
    lines.push('');
  }

  lines.push('── Disclaimer ──');
  lines.push(summary.disclaimer);
  return lines.join('\n');
}

