
import { useRouter } from '@/router';
import { DESIGN } from '@/lib/design';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginTop: '22px' }}>
      <div style={{ fontSize: '14px', fontWeight: DESIGN.typography.weights.semibold }}>{title}</div>
      <div style={{ marginTop: '10px', fontSize: '14px', lineHeight: 1.7, color: DESIGN.colors.textSecondary }}>{children}</div>
    </div>
  );
}

export default function TermsPage() {
  const router = useRouter();

  return (
    <div style={{ padding: '28px 20px', maxWidth: '720px', margin: '0 auto' }}>
      <button
        type="button"
        onClick={() => router.back()}
        aria-label="Go back"
        style={{
          border: 'none',
          background: 'transparent',
          color: DESIGN.colors.gold,
          fontFamily: DESIGN.typography.sansSerif,
          fontSize: '15px',
          cursor: 'pointer',
          minHeight: '44px',
          padding: 0,
        }}
      >
        ← Back
      </button>

        <h1 style={{ margin: '12px 0 0', fontSize: '22px', fontWeight: DESIGN.typography.weights.light, fontFamily: DESIGN.typography.sansSerif }}>
          Terms of Service
        </h1>
        <div style={{ marginTop: '8px', fontSize: '12px', color: DESIGN.colors.textMuted }}>
          Last updated: February 2026
        </div>

        <Section title="What ALCHM Is">
          ALCHM is a self-reflection and journaling application with an AI companion called Khepera. It is designed to support personal
          reflection and emotional awareness.
        </Section>

        <Section title="What ALCHM Is Not">
          ALCHM is not a medical device, healthcare service, or substitute for professional mental health care. Khepera is an artificial
          intelligence, not a therapist, counselor, psychologist, or medical professional. ALCHM does not diagnose, treat, cure, or prevent any
          medical or mental health condition.
        </Section>

        <Section title="Crisis Resources">
          If you are in crisis, call or text{' '}
          <a href="tel:988" aria-label="Call 988 Suicide and Crisis Lifeline" style={{ color: DESIGN.colors.gold, textDecoration: 'underline' }}>
            988
          </a>{' '}
          (US), or contact your local emergency services.
        </Section>

        <Section title="AI-Generated Content">
          Khepera&apos;s reflections may be generated by artificial intelligence and may be inaccurate, incomplete, or inappropriate. Do not rely on
          reflections for medical or safety decisions.
        </Section>

        <Section title="Data & Privacy">
          Your journal data is stored locally on your device. See the Privacy Policy for details.
        </Section>

        <Section title="Contact">
          Support: <span style={{ color: DESIGN.colors.textPrimary }}>support@alchm.app</span>
        </Section>
    </div>
  );
}
