'use client';

import type React from 'react';
import { DESIGN } from '@/lib/design';

interface HealthDisclaimerProps {
  variant?: 'full' | 'compact' | 'onboarding';
}

export function HealthDisclaimer({ variant = 'full' }: HealthDisclaimerProps) {
  const isCompact = variant === 'compact';
  const showAiDisclosure = variant === 'onboarding';

  const linkStyle: React.CSSProperties = {
    color: DESIGN.colors.gold,
    textDecoration: 'underline',
    fontFamily: DESIGN.typography.sansSerif,
  };

  const textStyle: React.CSSProperties = {
    margin: 0,
    fontFamily: DESIGN.typography.sansSerif,
    fontSize: isCompact ? DESIGN.typography.sizes.xs : DESIGN.typography.sizes.sm,
    color: isCompact ? DESIGN.colors.textMuted : DESIGN.colors.textSecondary,
    lineHeight: String(DESIGN.typography.lineHeights.relaxed),
  };

  if (isCompact) {
    return (
      <p style={textStyle}>
        ALCHM is not therapy. Khepera is AI, not a medical professional. In crisis, call{' '}
        <a href="tel:988" style={linkStyle} aria-label="Call 988 Suicide and Crisis Lifeline">
          988
        </a>
        .
      </p>
    );
  }

  return (
    <div
      style={{
        borderRadius: DESIGN.radius.lg,
        border: `1px solid ${DESIGN.colors.borderLight}`,
        background: DESIGN.colors.cardBg,
        padding: DESIGN.spacing.md,
      }}
    >
      <p style={textStyle}>
        ALCHM is a self-reflection and journaling tool. Khepera is an AI reflection system, not a
        therapist, counselor, or medical professional. ALCHM does not diagnose, treat, cure, or prevent any condition.
      </p>
      <p style={{ ...textStyle, marginTop: DESIGN.spacing.sm }}>
        If you are in crisis, call or text{' '}
        <a href="tel:988" style={linkStyle} aria-label="Call 988 Suicide and Crisis Lifeline">
          988
        </a>{' '}
        or text HOME to{' '}
        <a href="sms:741741&body=HOME" style={linkStyle} aria-label="Text Crisis Text Line (HOME to 741741)">
          741741
        </a>
        .
      </p>
      {showAiDisclosure ? (
        <p style={{ ...textStyle, marginTop: DESIGN.spacing.sm, fontStyle: 'italic' }}>
          Khepera&apos;s reflections are generated by AI. They are not professional advice.
        </p>
      ) : null}
    </div>
  );
}
