'use client';

import type React from 'react';
import Link from 'next/link';
import { SanctuaryLayout } from '@/components/ui/SanctuaryLayout';
import { SanctuaryHeader } from '@/components/ui/SanctuaryHeader';
import { SanctuaryCard } from '@/components/ui/SanctuaryCard';
import { SanctuaryText } from '@/components/ui/SanctuaryText';
import { DESIGN } from '@/lib/design';

export default function TermsPage() {
  return (
    <SanctuaryLayout header={<SanctuaryHeader title="Terms" showBack />}>
      <div style={{ display: 'grid', gap: DESIGN.spacing.md }}>
        <SanctuaryCard elevated>
          <SanctuaryText variant="title" style={{ marginBottom: DESIGN.spacing.xs }}>
            Terms of Service
          </SanctuaryText>
          <SanctuaryText variant="caption">Last updated: February 2026</SanctuaryText>
        </SanctuaryCard>

        <SanctuaryCard>
          <Section title="What ALCHM Is">
            <P>
              ALCHM is a self-reflection and journaling application. It includes an AI reflection system called Khepera that
              reflects on what you write.
            </P>
          </Section>

          <Section title="What ALCHM Is Not">
            <P>
              ALCHM is not a medical device or healthcare service. Khepera is an AI reflection system, not a therapist,
              counselor, psychologist, or medical professional. ALCHM does not diagnose, treat, cure, or prevent any
              condition.
            </P>
            <P>
              If you are in crisis, call or text <a href="tel:988" style={linkStyle} aria-label="Call 988 Suicide and Crisis Lifeline">988</a>{' '}
              or text HOME to{' '}
              <a href="sms:741741&body=HOME" style={linkStyle} aria-label="Text Crisis Text Line (HOME to 741741)">741741</a>.
            </P>
          </Section>

          <Section title="AI-Generated Content">
            <P>
              Khepera&apos;s reflections are generated by artificial intelligence. They may be inaccurate, incomplete,
              or not appropriate for your situation. Do not rely on AI-generated content as professional advice.
            </P>
          </Section>

          <Section title="Privacy">
            <P>
              Journal entries may be queued locally on your device and, when you are signed in, stored in ALCHM&apos;s
              cloud data store. Requested reflections use an authenticated server-controlled gateway when that
              service is deployed and configured. See the{' '}
              <Link href="/privacy-policy/" style={linkStyle}>Privacy Policy</Link>.
            </P>
          </Section>

          <Section title="Age Requirement">
            <P>ALCHM is intended for users aged 17 and older.</P>
          </Section>

          <Section title="Contact">
            <P>Questions: support@alchm.app</P>
          </Section>
        </SanctuaryCard>
      </div>
    </SanctuaryLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ display: 'grid', gap: DESIGN.spacing.xs, marginBottom: DESIGN.spacing.md }}>
      <SanctuaryText variant="caption" style={{ color: DESIGN.colors.textPrimary }}>
        {title}
      </SanctuaryText>
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <SanctuaryText variant="body" style={{ margin: 0 }}>
      {children}
    </SanctuaryText>
  );
}

const linkStyle: React.CSSProperties = {
  color: DESIGN.colors.gold,
  textDecoration: 'underline',
  fontFamily: DESIGN.typography.sansSerif,
};
