#!/usr/bin/env bash
set -eu

cd "$(dirname "$0")/.."

echo "══════════════════════════════════════════"
echo "AUDIT FINDING VERIFICATION (alchm-v2)"
echo "══════════════════════════════════════════"

# ── FINDING 1: duplicate "* 2.*" files ──
F1=$(find . -name "* 2.*" -not -path './node_modules/*' | wc -l | tr -d ' ')
echo "F01 — Duplicate files:        $F1 (must be 0)"

# ── FINDING 2: TypeScript errors ──
F2=$(npx tsc --noEmit 2>&1 | rg -o "error TS[0-9]+" | wc -l | tr -d ' ')
echo "F02 — TypeScript errors:      $F2 (must be 0)"

# ── FINDING 3: Dead code directories ──
F3=0
for dir in cultural middleware policies security monitoring ai examples __tests__ admin; do
  if [ -d "src/$dir" ]; then echo "  ❌ src/$dir exists"; F3=$((F3+1)); fi
done
echo "F03 — Dead directories:       $F3 (must be 0)"

# ── FINDING 4: Dead lib files ──
F4=0
for f in stripe.ts openaiWithRateLimit.ts hipaaAuditLogger.ts advancedAI.ts firebaseAdmin.ts aiService.ts; do
  if [ -f "src/lib/$f" ]; then echo "  ❌ src/lib/$f exists"; F4=$((F4+1)); fi
done
echo "F04 — Dead lib files:         $F4 (must be 0)"

# ── FINDING 5: Dead middleware files ──
F5=0
[ -f "src/middleware.ts" ] && F5=$((F5+1))
[ -f "src/middleware-legal.ts" ] && F5=$((F5+1))
echo "F05 — Dead middleware:        $F5 (must be 0)"

# ── FINDING 6: Dead mobile files ──
F6=0
for f in emergency-mode.tsx mobile-trauma-test.js offline-crisis-resources.ts; do
  if [ -f "src/mobile/$f" ]; then F6=$((F6+1)); fi
done
echo "F06 — Dead mobile files:      $F6 (must be 0)"

# ── FINDING 7: Dead API routes ──
F7=0
[ -d "src/app/api" ] && F7=$((F7+1))
[ -d "src/app/api.disabled" ] && F7=$((F7+1))
echo "F07 — Dead API routes:        $F7 (must be 0)"

# ── FINDING 8: Debug/test/admin routes in build ──
F8=0
for route in test test-hooks test-simple debug-hooks debug-react admin; do
  if [ -d "out/$route" ]; then echo "  ❌ $route in build output"; F8=$((F8+1)); fi
done
echo "F08 — Debug routes in build:  $F8 (must be 0)"

# ── FINDING 9: window.location for internal navigation ──
F9=$(
  { rg -n "window\\.location" src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } \
    | rg -v "tel:|sms:|mailto:" \
    | rg -v "typeof window" \
    | wc -l | tr -d ' '
)
echo "F09 — window.location (non-external): $F9 (must be 0)"

# ── FINDING 10: Direct localStorage access outside storage.ts ──
F10=$(
  { rg -n "localStorage\\." src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } \
    | rg -v "src/lib/storage\\.ts" \
    | wc -l | tr -d ' '
)
echo "F10 — Direct localStorage:    $F10 (must be 0)"

# ── FINDING 11: console.log in production code ──
F11=$({ rg -n "console\\.log" src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F11 — console.log:            $F11 (must be 0)"

# ── FINDING 12: Hardcoded API keys ──
F12=$({ rg -n "sk-ant|sk_live|pk_live|sk_test" src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F12 — Hardcoded keys:         $F12 (must be 0)"

# ── FINDING 13: process.env non-NEXT_PUBLIC in client code ──
F13=$(
  { rg -n "process\\.env\\." src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } \
    | rg -v "NEXT_PUBLIC_|NODE_ENV" \
    | wc -l | tr -d ' '
)
echo "F13 — Non-public env vars:    $F13 (must be 0)"

# ── FINDING 14: Sentry references ──
F14=$({ rg -n "sentry|Sentry|@sentry" src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F14 — Sentry references:      $F14 (must be 0)"

# ── FINDING 15: Missing 'use client' on files with hooks ──
F15=0
while IFS= read -r f; do
  HOOKS=$(grep -c "useState\\|useEffect\\|useRouter\\|useCallback\\|useRef\\|useMemo\\|useContext" "$f" 2>/dev/null || true)
  CLIENT=$(grep -c "'use client'" "$f" 2>/dev/null || true)
  if [ "$HOOKS" -gt 0 ] && [ "$CLIENT" -eq 0 ]; then
    echo "  ❌ $f has hooks but no 'use client'"
    F15=$((F15+1))
  fi
done < <(find src -name "*.tsx" | sort)
echo "F15 — Missing 'use client':   $F15 (must be 0)"

# ── FINDING 16: Health disclaimer ──
F16=$({ rg -l "not.*therapist|not.*medical professional|not.*counselor" src -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F16 — Health disclaimer files: $F16 (must be ≥ 2)"

# ── FINDING 17: AI disclosure ──
F17=$({ rg -l "artificial intelligence|generated by AI|AI companion" src -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F17 — AI disclosure files:    $F17 (must be ≥ 1)"

# ── FINDING 18: Privacy policy page ──
F18=0; [ -f "src/app/privacy/page.tsx" ] && F18=1
echo "F18 — Privacy policy page:    $F18 (must be 1)"

# ── FINDING 19: Terms page ──
F19=0; [ -f "src/app/terms/page.tsx" ] && F19=1
echo "F19 — Terms of service page:  $F19 (must be 1)"

# ── FINDING 20: Fake StoreKit / localStorage purchases ──
F20=$({ rg -n "localStorage.*purchase|localStorage.*subscription|localStorage.*tier.*paid" src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F20 — Fake purchase logic:    $F20 (must be 0)"

# ── FINDING 21: 988 in root layout ──
F21=$(grep -c "988\|CrisisFooter" src/app/layout.tsx 2>/dev/null || echo 0)
echo "F21 — 988 in root layout:     $F21 (must be ≥ 1)"

# ── FINDING 22: aria-label coverage ──
F22=$({ rg -n "aria-label" src -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F22 — aria-labels:            $F22 (must be ≥ 20)"

# ── FINDING 23: Capacitor server.url set ──
F23=$(grep -n "server:" capacitor.config.ts 2>/dev/null | wc -l | tr -d ' ')
echo "F23 — server.url in config:   $F23 (must be 0)"

# ── FINDING 24: Missing loading states ──
F24=0
while IFS= read -r f; do
  ROUTE=$(echo "$f" | sed 's|src/app||;s|/page.tsx||;s|^$|/|')
  echo "$ROUTE" | rg -q "^/(privacy|terms)/?$" && continue
  HAS=$(rg -n "loading|Loading|skeleton|Skeleton|PageState" "$f" 2>/dev/null | wc -l | tr -d ' ')
  if [ "$HAS" -eq 0 ]; then echo "  ⚠️ $ROUTE — no loading state"; F24=$((F24+1)); fi
done < <(find src/app -name "page.tsx" | sort)
echo "F24 — Pages without loading:  $F24 (must be 0)"

# ── FINDING 25: Khepera prompt safety ──
F25_THERAPIST=$(grep -rl "not.*therapist\|not.*counselor\|not.*medical" src/lib/khepera.ts 2>/dev/null | wc -l | tr -d ' ')
F25_988=$(grep -c "988" src/lib/khepera.ts 2>/dev/null || echo 0)
F25_AI=$(grep -c "AI companion\|artificial intelligence" src/lib/khepera.ts 2>/dev/null || echo 0)
echo "F25 — Khepera prompt safety:  therapist=$F25_THERAPIST, 988=$F25_988, AI=$F25_AI (all must be ≥ 1)"

# ── FINDING 26: Orphan files ──
F26=0
FILES=$(find src/lib src/components src/app -type f \( -name "*.ts" -o -name "*.tsx" \) | sort)
for f in $FILES; do
  case "$f" in
    src/app/layout.tsx|src/app/*/page.tsx|src/app/page.tsx) continue ;;
  esac
  # Best-effort: if no other file mentions this exact module path, consider it orphan.
  mod="${f#src/}"; mod="${mod%.ts}"; mod="${mod%.tsx}"
  refs=$({ rg -n "from ['\\\"]@/${mod}['\\\"]|from ['\\\"]\\./${mod##*/}['\\\"]|from ['\\\"]\\.\\./${mod##*/}['\\\"]" src -g'*.ts' -g'*.tsx' 2>/dev/null || true; } | wc -l | tr -d ' ')
  if [ "$refs" -eq 0 ]; then echo "  ⚠️ ORPHAN: $f"; F26=$((F26+1)); fi
done
echo "F26 — Orphan files:           $F26 (must be 0)"

# ── FINDING 27: Total src files ──
F27=$(find src -type f | wc -l | tr -d ' ')
echo "F27 — Total src files:        $F27 (must be under 60)"

# ── FINDING 28: Build output ──
F28=$(find out -name "index.html" 2>/dev/null | wc -l | tr -d ' ')
echo "F28 — Built pages:            $F28 (must be ≥ 12)"

# ── FINDING 29: iOS sync ──
npx cap sync ios >/dev/null 2>&1 || true
F29=$(find ios/App/App/public -name "index.html" 2>/dev/null | wc -l | tr -d ' ')
echo "F29 — iOS synced pages:       $F29 (must be ≥ 12)"

# ── FINDING 30: Bundle size ──
F30=$(du -sh out/ 2>/dev/null | cut -f1 || echo "?")
echo "F30 — Bundle size:            $F30"

# ── FINDING 31: Dead type files ──
F31=0
for f in career-schema.ts identity-pathway-schema.ts; do
  [ -f "src/types/$f" ] && F31=$((F31+1))
done
echo "F31 — Dead type files:        $F31 (must be 0)"

# ── FINDING 32: Telemetry in layout ──
F32=$(rg -n "Telemetry|telemetry" src/app/layout.tsx 2>/dev/null | wc -l | tr -d ' ')
echo "F32 — Telemetry in layout:    $F32 (must be 0)"

# ── FINDING 33: BlockInProduction ──
F33=0; [ -f "src/components/BlockInProduction.tsx" ] && F33=1
echo "F33 — BlockInProduction:      $F33 (must be 0)"

# ── FINDING 34: page-original.tsx ──
F34=0; [ -f "src/app/page-original.tsx" ] && F34=1
echo "F34 — page-original.tsx:      $F34 (must be 0)"

# ── FINDING 35: viewport-fit=cover ──
F35=$({ rg -n "viewport-fit.*cover|viewport-fit=cover" src/app/layout.tsx out/index.html 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F35 — viewport-fit=cover:     $F35 (must be ≥ 1)"

# ── FINDING 36: Safe area CSS ──
F36=$({ rg -n "safe-area-inset" src/app/globals.css src/styles/mobile.css 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "F36 — Safe area rules:        $F36 (must be ≥ 4)"

# ── FINDING 37: App Store metadata ──
F37=0; [ -f "APP_STORE_METADATA.md" ] && F37=1
echo "F37 — App Store metadata:     $F37 (must be 1)"

echo ""
echo "══════════════════════════════════════════"
echo "SUMMARY"
echo "══════════════════════════════════════════"

PASS=0; FAIL=0
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 20 23 26 31 32 33 34; do
  VAR="F${i}"
  VAL=$(eval echo \$$VAR)
  if [ "$VAL" = "0" ]; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); fi
done
for i in 16 17 18 19 21 28 29 35 36 37; do
  VAR="F${i}"
  VAL=$(eval echo \$$VAR)
  if [ "$VAL" -ge 1 ] 2>/dev/null; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); fi
done
[ "$F22" -ge 20 ] && PASS=$((PASS+1)) || FAIL=$((FAIL+1))
[ "$F27" -lt 60 ] && PASS=$((PASS+1)) || FAIL=$((FAIL+1))

echo "PASSED: $PASS"
echo "FAILED: $FAIL"
echo ""
if [ "$FAIL" -eq 0 ]; then
  echo "✅ ALL AUDIT FINDINGS RESOLVED"
else
  echo "❌ $FAIL FINDINGS STILL OPEN — FIX BEFORE CONTINUING"
fi
