'use client';

import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#A8B09E] to-[#8B9A7C] flex flex-col">
      <header className="px-6 pt-14 pb-6">
        <Link href="/settings/" className="text-white/60 text-base mb-4 inline-block">
          ← Back
        </Link>
        <h1 className="text-white text-3xl font-light">Medical Disclaimer</h1>
      </header>

      <div className="flex-1 px-6 overflow-y-auto">
        <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 border border-white/10 space-y-6">
          
          <section>
            <h2 className="text-white/90 text-lg font-medium mb-3">Not Medical Advice</h2>
            <p className="text-white/70 text-sm leading-relaxed">
              ALCHM is a wellness application designed to support self-reflection, 
              mindfulness, and personal growth. It is not intended to be a substitute 
              for professional medical advice, diagnosis, or treatment.
            </p>
          </section>

          <section>
            <h2 className="text-white/90 text-lg font-medium mb-3">Seek Professional Help</h2>
            <p className="text-white/70 text-sm leading-relaxed">
              If you are experiencing a mental health crisis, severe emotional distress, 
              or thoughts of self-harm, please contact a qualified mental health 
              professional immediately or call emergency services.
            </p>
          </section>

          <section>
            <h2 className="text-white/90 text-lg font-medium mb-3">Crisis Resources</h2>
            <p className="text-white/70 text-sm leading-relaxed mb-3">
              If you are in the United States and experiencing a crisis:
            </p>
            <div className="bg-white/10 rounded-xl p-4">
              <p className="text-white/90 text-base font-medium">988 Suicide & Crisis Lifeline</p>
              <p className="text-white/60 text-sm">Call or text 988, available 24/7</p>
            </div>
          </section>

          <section>
            <h2 className="text-white/90 text-lg font-medium mb-3">AI Companion</h2>
            <p className="text-white/70 text-sm leading-relaxed">
              Khepera, the AI companion in ALCHM, provides supportive responses based on 
              your journal entries. These responses are generated by artificial intelligence 
              and should not be considered professional therapeutic advice. Khepera is 
              designed to offer reflection and support, not clinical treatment.
            </p>
          </section>

          <section>
            <h2 className="text-white/90 text-lg font-medium mb-3">Your Responsibility</h2>
            <p className="text-white/70 text-sm leading-relaxed">
              By using ALCHM, you acknowledge that you are responsible for your own 
              mental health and wellbeing. The app is a tool for self-reflection, 
              not a replacement for professional care.
            </p>
          </section>

        </div>
        
        {/* Crisis Support Footer */}
        <div className="mt-8 pb-8 pt-6">
          <p className="text-white/30 text-xs text-center tracking-wide">
            Crisis support available · 988
          </p>
        </div>

      </div>
    </div>
  );
}